### ISSUE TITLE
PRACTICA 1

### ISSUE THREAD

**Issue by isaireyesp1** [SistemasTecTlaxiaco/expresiones-boolenas-team-eduardo-tomas-1as#2]
[MATE PRACTICA 1 UNIDAD V.pdf](https://github.com/SistemasTecTlaxiaco/expresiones-boolenas-team-eduardo-tomas-1as/files/7731091/MATE.PRACTICA.1.UNIDAD.V.pdf)

**Comment by lucero012** [comment]
En la portada 25 : cumple con los criterios
Procedimiento 17 : tiene objetivo, pero le falta la descripción de las actividades
Figuras ilustraciones y fotografía 25 : porque cumple completo con los criterios a evaluar
Resultados y conclusión 25 : porque tiene resultados y su conclusión
también les falta estructurar y poner las instrucciones en cada punto para saber que se esta haciendo.

calificación = 92/100 = 27.6/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
